language: ruby
sudo: false
cache: bundler
bundler_args: --without development
rvm:
  - "2.1.5"

# Set the timezone for phantomjs with TZ
# Set the timezone for karma with TIMEZONE
#
# The test cases are roughly split according to their test times.
# It would be better to use https://github.com/ArturT/knapsack.
env:
  global:
    - TZ="Australia/Melbourne"
    - TIMEZONE="Australia/Melbourne"
  matrix:
    - TEST_CASES="./spec/features/admin" GITHUB_DEPLOY="true"
    - TEST_CASES="./spec/features/consumer ./spec/serializers ./spec/performance"
    - TEST_CASES="./spec/models"
    - TEST_CASES="./spec/controllers ./spec/views ./spec/jobs"
    - TEST_CASES="./spec/requests ./spec/helpers ./spec/mailers ./spec/lib" KARMA="true"

before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/application.yml.example config/application.yml
  - RAILS_ENV=test bundle exec rake db:create db:schema:load
  - >
    if [ "$KARMA" = "true" ]; then
      npm install karma@0.12.31
      npm install karma-jasmine@0.1.5
      npm install karma-phantomjs-launcher@0.1.4
      npm install karma-coffee-preprocessor@0.2.1
      npm install -g karma-cli@0.0.4
    fi

script:
  - '[ "$KARMA" = "true" ] && bundle exec rake karma:run || echo "Skipping karma run"'
  - "bundle exec rspec $TEST_CASES"

after_success:
  - >
    if [ "$GITHUB_DEPLOY" = "true" -a "$TRAVIS_PULL_REQUEST" = "false" -a -n "$TRAVIS_BRANCH" -a -n "$GITHUB_API_SECRET" ]; then
      description="`git show "$TRAVIS_BRANCH" -s --oneline --no-color`"
      data="{
        \"ref\":\"$TRAVIS_BRANCH\",
        \"description\":\"$description\",
        \"environment\":\"staging\",
        \"required_contexts\":[]}"
      curl -u "$GITHUB_API_SECRET" -d "$data" "https://api.github.com/repos/$TRAVIS_REPO_SLUG/deployments"
    else
      echo "Not deploying on this build."
    fi

notifications:
  email: false
