language: ruby
sudo: false
cache: bundler
bundler_args: --without development
rvm:
  - "2.1.5"

# Set the timezone for phantomjs with TZ
# Set the timezone for karma with TIMEZONE
#
# The test cases are roughly split according to their test times.
# It would be better to use https://github.com/ArturT/knapsack.
env:
  global:
    - TZ="Australia/Melbourne"
    - TIMEZONE="Australia/Melbourne"
    - CI_NODE_TOTAL=5
  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1
    - CI_NODE_INDEX=2
    - CI_NODE_INDEX=3
    - CI_NODE_INDEX=4 KARMA="true" GITHUB_DEPLOY="true"

before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/application.yml.example config/application.yml
  - RAILS_ENV=test bundle exec rake db:create db:schema:load
  - >
    if [ "$KARMA" = "true" ]; then
      npm install karma@0.12.31
      npm install karma-jasmine@0.1.5
      npm install karma-phantomjs-launcher@0.1.4
      npm install karma-coffee-preprocessor@0.2.1
      npm install -g karma-cli@0.0.4
    fi

script:
  - 'if [ "$KARMA" = "true" ]; then bundle exec rake karma:run; else echo "Skipping karma run"; fi'
  #- "KNAPSACK_GENERATE_REPORT=true bundle exec rspec spec"
  - "bundle exec rake 'knapsack:rspec[--tag ~performance]'"

notifications:
  email: false
